pipeline:
- name: tokenizer_whitespace
- name: ner_crf
- name: ner_synonyms
- name: intent_featurizer_count_vectors
  token_pattern: (?u)\b\w+\b
- name: intent_classifier_tensorflow_embedding
- name: ner_duckling_http
  url: http://localhost:8000
  dimensions:
  - number
language: en
