pipeline:
- name: tokenizer_whitespace
- name: ner_crf
- name: intent_featurizer_count_vectors
  OOV_token: oov
  token_pattern: (?u)\b\w+\b
- name: intent_classifier_tensorflow_embedding
- name: ner_duckling_http
  url: http://localhost:8000
  dimensions:
  - email
  - number
  - amount-of-money
language: en
